#!/bin/sh

set -e

export TARGET=/usr/local/docker/bin
export PATH=$PATH:$TARGET

mkdir -p ${TARGET}

curl --silent --location \
    https://raw.githubusercontent.com/houseabsolute/ubi/master/bootstrap/bootstrap-ubi.sh |
    sh

ubi -p talss89/envtmpl -t v0.2.0 -i ${TARGET}
